/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import controller.LivroController;
import controller.VendaController;
import java.awt.Component;
import static java.awt.Component.RIGHT_ALIGNMENT;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import model.Cliente;
import model.Livro;
import model.Venda;

/**
 *
 * @author gusta
 */
public class FrAltVenda extends javax.swing.JDialog {

    private int idVenda;
    private javax.swing.JPanel jPanelLivros = new javax.swing.JPanel();
    private Map<String, Cliente> mapaClientes = new HashMap<>();

    public FrAltVenda(java.awt.Frame parent, boolean modal, int idVenda) {
        super(parent, modal);
        this.idVenda = idVenda;
        initComponents();
        jPanelLivros.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        jPanel1.add(jPanelLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 700, 250));


        carregarVenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbQuantidade = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        edtQuantidade = new javax.swing.JTextField();
        lbIdCliente1 = new javax.swing.JLabel();
        edtData = new javax.swing.JTextField();
        lbLivro = new javax.swing.JLabel();
        btmSalvar = new javax.swing.JButton();
        btmCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbQuantidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbQuantidade.setForeground(new java.awt.Color(204, 204, 0));
        lbQuantidade.setText("Quantidade");
        jPanel1.add(lbQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lbData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbData.setForeground(new java.awt.Color(204, 204, 0));
        lbData.setText("Data");
        jPanel1.add(lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        edtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtQuantidadeActionPerformed(evt);
            }
        });
        jPanel1.add(edtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 130, -1));

        lbIdCliente1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbIdCliente1.setForeground(new java.awt.Color(204, 204, 0));
        lbIdCliente1.setText("ID Cliente");
        jPanel1.add(lbIdCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel1.add(edtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, -1));

        lbLivro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbLivro.setForeground(new java.awt.Color(204, 204, 0));
        lbLivro.setText("Livro");
        jPanel1.add(lbLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btmSalvar.setBackground(new java.awt.Color(255, 255, 153));
        btmSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmSalvar.setBorderPainted(false);
        btmSalvar.setContentAreaFilled(false);
        btmSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmSalvar.setFocusPainted(false);
        btmSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btmSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 120, 40));

        btmCancelar.setBackground(new java.awt.Color(255, 255, 153));
        btmCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmCancelar.setBorderPainted(false);
        btmCancelar.setContentAreaFilled(false);
        btmCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmCancelar.setFocusPainted(false);
        btmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btmCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 120, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Alterar Venda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_salvar.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_voltar.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 130, 40));

        comboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 100, 400, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalvarActionPerformed
        salvarVenda();

    }//GEN-LAST:event_btmSalvarActionPerformed

    private void btmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCancelarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btmCancelarActionPerformed

    private void edtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtQuantidadeActionPerformed

    private void preencherComboBoxCliente() {
        ClienteController clienteController = new ClienteController();
        List<Cliente> listaClientes = clienteController.listarTodos();

        comboCliente.removeAllItems();
        mapaClientes.clear();

        for (Cliente cliente : listaClientes) {
            String nome = cliente.getNome();
            comboCliente.addItem(nome);
            mapaClientes.put(nome, cliente);
        }
    }

    private void carregarVenda() {
        VendaController vendaController = new VendaController();
        Venda venda = vendaController.getVendaPorId(idVenda);

        preencherComboBoxCliente();

        Cliente cliente = new ClienteController().buscarPorId(venda.getIdCliente());
        comboCliente.setSelectedItem(cliente.getNome());
        edtData.setText(venda.getDataVenda().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        for (Map.Entry<Livro, Integer> entry : venda.getLivrosVendidos().entrySet()) {
            adicionarLivroEQuantidade(entry.getKey(), entry.getValue());
        }
    }

private void adicionarLivroEQuantidade(Livro livro, Integer quantidade) {
    // Painel para um único par Livro + Quantidade
    JPanel painelLivroQuant = new JPanel();
    painelLivroQuant.setBorder(new EmptyBorder(2, 0, 2, 0)); // top, left, bottom, right
    painelLivroQuant.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 2)); // Reduzido vgap

    // Cria o JComboBox de livros com todos os livros disponíveis
    JComboBox<Livro> comboLivros = new JComboBox<>();
    LivroController livroController = new LivroController();
    List<Livro> listaLivros = livroController.listarTodos();
    for (Livro l : listaLivros) {
        comboLivros.addItem(l);
    }
    for (int i = 0; i < comboLivros.getItemCount(); i++) {
        Livro item = comboLivros.getItemAt(i);
        if (item != null && item.getId() == livro.getId()) {
            comboLivros.setSelectedIndex(i);
            break;
        }
    }

    // Cria o JComboBox de quantidade
    JComboBox<Integer> comboQuant = new JComboBox<>();
    for (int i = 1; i <= 10; i++) {
        comboQuant.addItem(i);
    }
    comboQuant.setSelectedItem(quantidade);

    // Tamanho dos JComboBox
    comboLivros.setPreferredSize(new java.awt.Dimension(180, comboLivros.getPreferredSize().height));
    comboQuant.setPreferredSize(new java.awt.Dimension(80, comboQuant.getPreferredSize().height));

    painelLivroQuant.add(comboLivros);
    painelLivroQuant.add(comboQuant);

    // Certifica-se que jPanelLivros use um alinhamento à esquerda e layout vertical
    jPanelLivros.setLayout(new BoxLayout(jPanelLivros, BoxLayout.Y_AXIS));
    jPanelLivros.setAlignmentX(RIGHT_ALIGNMENT);

    painelLivroQuant.setAlignmentX(RIGHT_ALIGNMENT); // Alinha o painel individual à esquerda

    jPanelLivros.add(painelLivroQuant);
    jPanelLivros.revalidate();
    jPanelLivros.repaint();
}

    private void salvarVenda() {
        try {
            String nomeSelecionado = comboCliente.getSelectedItem().toString();
            Cliente cliente = mapaClientes.get(nomeSelecionado); // CERTO

            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "Selecione um cliente.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String dataStr = edtData.getText().trim();
            LocalDate dataVenda = LocalDate.parse(dataStr, DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            Map<Livro, Integer> livrosVendidos = new HashMap<>();
            for (Component comp : jPanelLivros.getComponents()) {
                if (comp instanceof JPanel) {
                    JPanel painel = (JPanel) comp;
                    JComboBox<Livro> comboLivros = (JComboBox<Livro>) painel.getComponent(0);
                    JComboBox<Integer> comboQuant = (JComboBox<Integer>) painel.getComponent(1);

                    Livro livro = (Livro) comboLivros.getSelectedItem();
                    Integer quantidade = (Integer) comboQuant.getSelectedItem();

                    if (livro != null && quantidade != null) {
                        livrosVendidos.put(livro, quantidade);
                    }
                }
            }

            if (livrosVendidos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Adicione pelo menos um livro à venda.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Venda venda = new Venda(idVenda, cliente, livrosVendidos, dataVenda);
            VendaController vendaController = new VendaController();
            vendaController.alterarVenda(venda);

            JOptionPane.showMessageDialog(this, "Venda atualizada com sucesso.");
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar a venda: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private Cliente buscarClientePorId(int id) {
        // Lógica para buscar o cliente pelo ID, pode ser feito via controlador ou banco de dados
        // Exemplo de implementação fictícia:
        ClienteController clienteController = new ClienteController();
        return clienteController.buscarPorId(id);
    }

    // Método fictício para buscar livro por título
    private Livro buscarLivroPorTitulo(String titulo) {
        // Lógica de busca pelo título (pode ser feito via controlador ou diretamente no banco)
        // Este é apenas um exemplo
        return new Livro();  // Retorna um novo livro, a lógica de busca precisa ser implementada
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltVenda dialog = new FrAltVenda(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCancelar;
    private javax.swing.JButton btmSalvar;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextField edtQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbIdCliente1;
    private javax.swing.JLabel lbLivro;
    private javax.swing.JLabel lbQuantidade;
    // End of variables declaration//GEN-END:variables
}
