/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import controller.FuncionarioController;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Funcionario;

/**
 *
 * @author thain
 */
public class FrAltFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form FrAltEstoque
     */
    public FrAltFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    FuncionarioController controller = new FuncionarioController();
    Funcionario cl = new Funcionario();
    
    
    public void gravarFuncionario() {
    // Cria o objeto Funcionario
    Funcionario funcionario = new Funcionario();

    // Preenche os dados do funcionário capturados do formulário
    funcionario.setId(Integer.parseInt(edtCodigo.getText().trim())); // Captura o ID
    funcionario.setNome(edtNome.getText().trim()); // Nome do funcionário
    funcionario.setCargo(edtCargo.getText().trim()); // Cargo do funcionário
    funcionario.setEmail(edtEmail.getText().trim()); // Email do funcionário
    funcionario.setTelefone(edtTelefone.getText().trim()); // Telefone do funcionário
    funcionario.setAtivo(chkAtivo.isSelected()); // Estado ativo/inativo

    // Instancia o controlador para salvar os dados
    FuncionarioController controller = new FuncionarioController();

    // Decide entre inserir ou atualizar com base no ID
    if (funcionario.getId() == 0) {
        // Inserção de novo funcionário
        if (controller.inserir(funcionario)) {
            JOptionPane.showMessageDialog(null, "Funcionário: " + funcionario.getNome() + " gravado com sucesso!");
            this.dispose(); // Fecha a tela
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao gravar o funcionário!");
        }
    } else {
        // Atualização de funcionário existente
        if (controller.atualizar(funcionario)) {
            JOptionPane.showMessageDialog(null, "Funcionário: " + funcionario.getNome() + " atualizado com sucesso!");
            this.dispose(); // Fecha a tela
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar o funcionário!");
        }
    }
    }
    
    public void carregarFuncionario() {
    // Busca os dados do funcionário no banco
    FuncionarioController controller = new FuncionarioController();
    Funcionario funcionario = controller.buscarPorId(Integer.parseInt(edtCodigo.getText().trim())); // Busca pelo ID

    // Preenche os campos do formulário com os dados do funcionário
    edtCodigo.setText(String.valueOf(funcionario.getId())); // ID do funcionário
    edtNome.setText(funcionario.getNome()); // Nome do funcionário
    edtCargo.setText(funcionario.getCargo()); // Cargo do funcionário
    edtEmail.setText(funcionario.getEmail()); // Email do funcionário
    edtTelefone.setText(funcionario.getTelefone()); // Telefone do funcionário
    chkAtivo.setSelected(funcionario.isAtivo()); // Estado ativo/inativo
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtCargo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JTextField();
        chkAtivo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alterar dados do Estoque");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 28, -1, -1));

        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 82, -1, -1));

        lblCargo.setText("Cargo");
        jPanel1.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 140, -1, -1));

        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 104, 141, -1));
        jPanel1.add(edtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 174, 141, -1));

        jButton1.setText("Voltar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 380, -1, -1));

        jButton2.setText("Salvar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 380, -1, -1));

        jButton3.setText("Alterar Titulo");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 298, -1, -1));

        lblCodigo.setText("Código");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 61, -1, -1));

        edtCodigo.setEditable(false);
        jPanel1.add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 57, 54, -1));

        lblTelefone.setText("Telefone");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 276, -1, -1));

        lblEmail.setText("E-mail");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 216, -1, -1));
        jPanel1.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 240, 141, -1));
        jPanel1.add(edtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 298, 141, -1));

        chkAtivo.setText("Ativo");
        jPanel1.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    
    public boolean verificarCampos() {
        // Captura os valores dos campos e remove espaços extras
        String nome = edtNome.getText().trim();
        String cargo = edtCargo.getText().trim();
        String email = edtEmail.getText().trim();
        String telefone = edtTelefone.getText().trim();

        // Validação do Nome
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo 'Nome' está vazio.");
            return false;
        }
        if (!nome.matches("^[A-Za-zÀ-ÖØ-öø-ÿ ]+$")) {
            JOptionPane.showMessageDialog(null, "Nome inválido! Use apenas letras e espaços.");
            return false;
        }

        // Validação do Cargo
        if (cargo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo 'Cargo' está vazio.");
            return false;
        }

        // Validação do Email
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo 'Email' está vazio.");
            return false;
        }
        if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(null, "E-mail inválido! Use o formato a@a.com.");
            return false;
        }

        // Validação do Telefone
        if (telefone.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo 'Telefone' está vazio.");
            return false;
        }
        if (!telefone.matches("^\\+?[0-9]{10,15}$")) {
            JOptionPane.showMessageDialog(null, "Telefone inválido! Use apenas números (com ou sem código de país).");
            return false;
        }

        // Se todos os campos são válidos
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltFuncionario dialog = new FrAltFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton chkAtivo;
    private javax.swing.JTextField edtCargo;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    // End of variables declaration//GEN-END:variables
}
