/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AutorController;
import controller.GeneroController;
import controller.GerenciadorConexao;
import controller.LivroController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Livro;
import java.util.List;
import java.util.stream.Collectors;
import java.util.Arrays;
import model.Autor;
import model.Genero;


/**
 *
 * @author gusta
 */
public class FrAltLivro extends javax.swing.JDialog {

    private Livro livro;
    private List<Autor> listaAutores;  // Lista de autores do banco
    private List<String> listaCategorias;  // Lista de categorias do banco

    public FrAltLivro(FrConLivros parent, boolean modal, Livro livro) {
        super(parent, modal);
        initComponents();
        this.livro = livro;

    // 👇 ISSO AQUI TEM QUE ESTAR DENTRO DO CONSTRUTOR
    listaCategorias = new ArrayList<>();
    listaCategorias.add("Romance");
    listaCategorias.add("Aventura");
    listaCategorias.add("Terror");
    listaCategorias.add("Suspense");
    listaCategorias.add("Ficção Científica");
    for (String genero : listaCategorias) {
        comboCategoria.addItem(genero);
    }


    preencherCampos();
    }

    FrAltLivro(FrConLivros aThis, boolean b, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtIdLivro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        edtTitulo = new javax.swing.JTextField();
        edtIsbn = new javax.swing.JTextField();
        edtPreco = new javax.swing.JTextField();
        edtAnoPublicacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboAutor = new javax.swing.JComboBox<>();
        comboCategoria = new javax.swing.JComboBox<>();
        btnAdicionarCategoria = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Código do livro:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 20));

        edtIdLivro.setEditable(false);
        edtIdLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIdLivroActionPerformed(evt);
            }
        });
        jPanel1.add(edtIdLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 47, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Autor ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        lbCategoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbCategoria.setForeground(new java.awt.Color(204, 204, 0));
        lbCategoria.setText("Categoria ID");
        jPanel1.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Título");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("ISBN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Preço");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("Ano de publicação");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(255, 255, 153));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setBorderPainted(false);
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setFocusPainted(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 120, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 153));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 120, 40));
        jPanel1.add(edtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 170, -1));
        jPanel1.add(edtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, -1));
        jPanel1.add(edtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, -1));
        jPanel1.add(edtAnoPublicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 130, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Alterar Livro");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_salvar.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 120, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_voltar.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 120, 40));

        comboAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        btnAdicionarCategoria.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarCategoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAdicionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnAdicionarCategoria.setText("Adicionar categoria");
        btnAdicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, 30));

        btnLimpar.setText("jButton1");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_logo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
// Atualiza os dados do livro com os valores dos campos
        livro.setTitulo(edtTitulo.getText());
        livro.setIsbn(edtIsbn.getText());
        livro.setPreco(Double.parseDouble(edtPreco.getText()));
        livro.setAnoPublicacao(Integer.parseInt(edtAnoPublicacao.getText()));

        // Atualiza o autor e a categoria selecionados
        livro.setIdAutor(listaAutores.get(comboAutor.getSelectedIndex()).getId());
        livro.setIdsCategorias(Arrays.asList(Integer.parseInt(getCategoriaSelecionada())));

        // Chama o método do controller para atualizar o livro no banco de dados
        LivroController livroController = new LivroController();
        livroController.atualizar(livro);

        JOptionPane.showMessageDialog(this, "Livro alterado com sucesso!");
        this.dispose();  // Fecha a tela de alteração


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtIdLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIdLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIdLivroActionPerformed

    private void btnAdicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCategoriaActionPerformed

    }//GEN-LAST:event_btnAdicionarCategoriaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

   // Inicializa a listaCategorias com valores fixos


// Método para preencher os campos com os dados do livro
private void preencherCampos() {
    if (livro != null) {
        edtTitulo.setText(livro.getTitulo());
        edtAnoPublicacao.setText(String.valueOf(livro.getAnoPublicacao()));
        edtPreco.setText(String.valueOf(livro.getPreco()));
        comboCategoria.setSelectedItem(livro.getCategorias());
        comboAutor.setSelectedItem(livro.getIdAutor()); // se usar nomes, talvez precise ajustar
    }


        // Seleciona a categoria no JComboBox com base no idCategoria do livro
        for (String genero : listaCategorias) {
            // Verifica se o ID da categoria está na lista de categorias do livro
            if (livro.getCategorias().contains(genero)) {
                comboCategoria.setSelectedItem(genero);  // Atribui a categoria diretamente
            }

        }
    }

    // Método para carregar os autores no ComboBox
    private void carregarAutores() {
        // Supondo que você tenha um método que retorna a lista de autores do banco
        AutorController autorController = new AutorController();
        listaAutores = autorController.listarTodos();  // Retorna lista de autores do banco

        // Adiciona cada autor no ComboBox
        for (Autor autor : listaAutores) {
            comboAutor.addItem(autor.getNome());  // Adiciona o nome do autor ao ComboBox
        }
    }

    // Método para carregar as categorias no ComboBox (como ID ou String)
    private void carregarCategorias() {
        // Cria uma instância do controller para acessar os dados das categorias
        GeneroController generoController = new GeneroController();

        // Obtém a lista de categorias do banco de dados
        List<Genero> listaCategorias = generoController.listarTodos();  // Retorna lista de objetos Genero

        // Adiciona cada categoria ao ComboBox
        for (Genero genero : listaCategorias) {
            comboCategoria.addItem(genero.getNome());  // Adiciona o nome da categoria ao ComboBox
        }
    }

    // Métodos para obter os valores selecionados nos ComboBox
    private Autor getAutorSelecionado() {
        return listaAutores.get(comboAutor.getSelectedIndex());  // Retorna o autor selecionado
    }

    private String getCategoriaSelecionada() {
        return (String) comboCategoria.getSelectedItem();  // Retorna a categoria selecionada
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCategoria;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboAutor;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JTextField edtAnoPublicacao;
    private javax.swing.JTextField edtIdLivro;
    private javax.swing.JTextField edtIsbn;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JTextField edtTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCategoria;
    // End of variables declaration//GEN-END:variables
}
