/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Cliente;
import utils.Utils;

/**
 *
 * @author thain
 */
public class FrAltCadUsuario extends javax.swing.JDialog {

    private int id;

    /**
     * Creates new form FrAltCadUsuario
     */
    public FrAltCadUsuario(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.id = id; // salva o id recebido
        carregarCliente(); // carrega os dados no formulário
    }

    ClienteController controller = new ClienteController();
    Cliente cl = new Cliente();

    FrAltCadUsuario(Object object, boolean rootPaneCheckingEnabled, int Id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void gravarCliente() {
        // Cria o objeto Cliente
        Cliente cliente = new Cliente();
        ClienteController controller = new ClienteController();

        // Preenche os dados do cliente capturados do formulário
        cliente.setId(this.id); // <- IMPORTANTE: definir o id para que seja atualizado
        cliente.setNome(edtNome.getText().trim());
        cliente.setEmail(edtEmail.getText().trim()); // <- Corrigido aqui
        cliente.setTelefone(edtTelefone.getText().trim()); // <- Adicionado caso exista campo telefone no modelo
        cliente.setDataNascimento(Utils.converterStringToDate(edtDataNasc.getText().trim()));
        cliente.setAtivo(chkAtivo.isSelected());

        // Atualiza o cliente no banco de dados
        if (controller.atualizar(cliente)) {
            JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro: Cliente não pôde ser atualizado.");
        }
    }

    public void carregarCliente() {
        // Busca os dados do cliente no banco de dados, utilizando o controlador
        ClienteController controller = new ClienteController();
        Cliente cliente = controller.buscarPorId(id); // Busca o cliente pelo ID

        // Preenche os campos do formulário com os dados do cliente
        String codigo = String.valueOf(cliente.getId()); // Converte o ID para String
        edtCodigo.setText(codigo); // Campo para o código/ID
        edtNome.setText(cliente.getNome()); // Nome do cliente
        edtEmail.setText((cliente.getEmail()));
        edtTelefone.setText(cliente.getTelefone()); // Telefone do cliente
        edtDataNasc.setText(Utils.converterDateToString(cliente.getDataNascimento())); // Converte a data de nascimento para String
        chkAtivo.setSelected(cliente.isAtivo()); // Define o estado ativo/inativo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        edtDataNasc = new javax.swing.JFormattedTextField();
        edtTelefone = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        chkAtivo = new javax.swing.JRadioButton();
        lblTelefone = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setText("Alteração nos dados do Cliente");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 28, -1, -1));

        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 72, -1, -1));

        lblEmail.setText("E-mail");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 134, -1, -1));

        lblDataNasc.setText("Data de Nascimento");
        jPanel1.add(lblDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 252, -1, -1));

        edtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel1.add(edtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 104, -1));
        jPanel1.add(edtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 222, 181, -1));

        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 98, 181, -1));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 382, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 382, -1, -1));

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 72, -1, -1));

        edtCodigo.setEditable(false);
        jPanel1.add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 68, 43, -1));

        chkAtivo.setText("Ativo");
        jPanel1.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 314, -1, -1));

        lblTelefone.setText("Telefone");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 186, -1, -1));
        jPanel1.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 156, 181, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if (verificarCampos()) {
            gravarCliente();
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    public boolean verificarCampos() {

        String nome = edtNome.getText().trim();
        String email = edtEmail.getText().trim();  // capturamos o e-mail do campo correto
        String telefone = edtTelefone.getText().trim();  // pegamos o telefone
        String dataNascimento = edtDataNasc.getText().trim();
        boolean ativo = chkAtivo.isSelected();

        // Validação do Nome
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Nome' está em branco.");
            return false;
        }
        if (!nome.matches("^[A-Za-zÀ-ÖØ-öø-ÿ ]+$")) {
            JOptionPane.showMessageDialog(this, "Nome inválido! Use apenas letras e espaços.");
            return false;
        }

        // Validação do Email
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Email' está em branco.");
            return false;
        }
        if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "E-mail inválido! Use o formato a@a.com.");
            return false;
        }

        // Validação do Telefone
        if (telefone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Telefone' está em branco.");
            return false;
        }
        if (!telefone.matches("^\\+?\\d{10,15}$")) {
            JOptionPane.showMessageDialog(this, "Telefone inválido! Use apenas números (com ou sem o código do país) e de 10 a 15 dígitos.");
            return false;
        }

        // Validação da Data de Nascimento
        if (dataNascimento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Data de Nascimento' está em branco.");
            return false;
        }
        if (!dataNascimento.matches("^\\d{2}/\\d{2}/\\d{4}$")) {
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida! Use o formato dd/mm/aaaa.");
            return false;
        }

        // Mensagem de validação (opcional)
        JOptionPane.showMessageDialog(this, "Todos os campos estão validados com sucesso!");
        return true; // Se todos os campos forem válidos
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltCadUsuario dialog = new FrAltCadUsuario(new javax.swing.JFrame(), true, 1); // exemplo com id = 1

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JRadioButton chkAtivo;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JFormattedTextField edtDataNasc;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
