/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AutorController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Autor;

/**
 *
 * @author gusta
 */
public class FrConAutores extends javax.swing.JDialog {

    /**
     * Creates new form FrConAutores
     */
    public FrConAutores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btmVoltar = new javax.swing.JButton();
        btmPesquisar = new javax.swing.JButton();
        btmEditar1 = new javax.swing.JButton();
        btmExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutores = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmVoltar.setBackground(new java.awt.Color(255, 255, 153));
        btmVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmVoltar.setBorderPainted(false);
        btmVoltar.setContentAreaFilled(false);
        btmVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmVoltar.setFocusPainted(false);
        btmVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btmVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 120, 40));

        btmPesquisar.setBackground(new java.awt.Color(255, 255, 153));
        btmPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmPesquisar.setBorderPainted(false);
        btmPesquisar.setContentAreaFilled(false);
        btmPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmPesquisar.setFocusPainted(false);
        btmPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btmPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 120, 50));

        btmEditar1.setBackground(new java.awt.Color(255, 255, 153));
        btmEditar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmEditar1.setBorderPainted(false);
        btmEditar1.setContentAreaFilled(false);
        btmEditar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmEditar1.setFocusPainted(false);
        btmEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmEditar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btmEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 110, 40));

        btmExcluir.setBackground(new java.awt.Color(255, 255, 153));
        btmExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmExcluir.setBorderPainted(false);
        btmExcluir.setContentAreaFilled(false);
        btmExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btmExcluir.setFocusPainted(false);
        btmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btmExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Autores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        tblAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAutores);
        if (tblAutores.getColumnModel().getColumnCount() > 0) {
            tblAutores.getColumnModel().getColumn(0).setResizable(false);
            tblAutores.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 290, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_voltar.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_excluir.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_editar.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_pesquisar.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 120, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_logo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 460, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPesquisarActionPerformed
        carregarTabela();
    }//GEN-LAST:event_btmPesquisarActionPerformed

    private void btmVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btmVoltarActionPerformed

    private void btmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmExcluirActionPerformed
        excluirAutor();
    }//GEN-LAST:event_btmExcluirActionPerformed

    private void btmEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEditar1ActionPerformed
        editarAutor();
    }//GEN-LAST:event_btmEditar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrConAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrConAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrConAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrConAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrConAutores dialog = new FrConAutores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblAutores.getModel();
        modelo.setRowCount(0); // limpa a tabela

        AutorController controller = new AutorController();

        try {
            for (Autor autor : controller.listarTodos()) {
                modelo.addRow(new Object[]{autor.getId(), autor.getNome()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar autores: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void excluirAutor() {
        int linhaSelecionada = tblAutores.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um autor para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este autor?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            int id = (int) tblAutores.getValueAt(linhaSelecionada, 0);
            AutorController controller = new AutorController();
            if (controller.excluir(id)) {
                JOptionPane.showMessageDialog(this, "Autor excluído com sucesso!");
                carregarTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir autor.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void editarAutor() {
        int linhaSelecionada = tblAutores.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um autor para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tblAutores.getValueAt(linhaSelecionada, 0);
        String nomeAtual = (String) tblAutores.getValueAt(linhaSelecionada, 1);

        String novoNome = JOptionPane.showInputDialog(this, "Editar nome do autor:", nomeAtual);

        if (novoNome != null && !novoNome.trim().isEmpty()) {
            Autor autor = new Autor(id, novoNome);
            AutorController controller = new AutorController();
            if (controller.atualizar(autor)) {
                JOptionPane.showMessageDialog(this, "Autor atualizado com sucesso!");
                carregarTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar autor.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else if (novoNome != null) {
            JOptionPane.showMessageDialog(this, "O nome do autor não pode estar vazio.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmEditar1;
    private javax.swing.JButton btmExcluir;
    private javax.swing.JButton btmPesquisar;
    private javax.swing.JButton btmVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutores;
    // End of variables declaration//GEN-END:variables
}
