/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.FrAltCadCliente;

/**
 *
 * @author thain
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logo3.png")).getImage());
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barMenu = new javax.swing.JMenuBar();
        meCadastro = new javax.swing.JMenu();
        miAltCadCliente = new javax.swing.JMenuItem();
        miLivros = new javax.swing.JMenuItem();
        miFuncionarios = new javax.swing.JMenuItem();
        miCategorias = new javax.swing.JMenuItem();
        miCadastrarAutor = new javax.swing.JMenuItem();
        meVendas = new javax.swing.JMenu();
        miRegistarVenda = new javax.swing.JMenuItem();
        miConsultarVenda = new javax.swing.JMenuItem();
        meSobre1 = new javax.swing.JMenu();
        miConCliente = new javax.swing.JMenuItem();
        miConLivro = new javax.swing.JMenuItem();
        miConCategoria = new javax.swing.JMenuItem();
        miConVendas = new javax.swing.JMenuItem();
        miConFuncionarios = new javax.swing.JMenuItem();
        meSobre = new javax.swing.JMenu();
        miInformações = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 652, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 480, 312));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 480));

        barMenu.setBackground(new java.awt.Color(204, 204, 0));

        meCadastro.setText("Cadastro");
        meCadastro.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N

        miAltCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        miAltCadCliente.setText("Clientes");
        miAltCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltCadClienteActionPerformed(evt);
            }
        });
        meCadastro.add(miAltCadCliente);

        miLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livros.png"))); // NOI18N
        miLivros.setText("Livros");
        miLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLivrosActionPerformed(evt);
            }
        });
        meCadastro.add(miLivros);

        miFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionarios.png"))); // NOI18N
        miFuncionarios.setText("Funcionários");
        miFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFuncionariosActionPerformed(evt);
            }
        });
        meCadastro.add(miFuncionarios);

        miCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categorias.png"))); // NOI18N
        miCategorias.setText("Categorias");
        miCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCategoriasActionPerformed(evt);
            }
        });
        meCadastro.add(miCategorias);

        miCadastrarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/autores.png"))); // NOI18N
        miCadastrarAutor.setText("Autores");
        miCadastrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarAutorActionPerformed(evt);
            }
        });
        meCadastro.add(miCadastrarAutor);

        barMenu.add(meCadastro);

        meVendas.setText("Vendas");
        meVendas.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N

        miRegistarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastro.png"))); // NOI18N
        miRegistarVenda.setText("Cadastrar Vendas");
        miRegistarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistarVendaActionPerformed(evt);
            }
        });
        meVendas.add(miRegistarVenda);

        miConsultarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consultar.png"))); // NOI18N
        miConsultarVenda.setText("Consultar Vendas");
        miConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarVendaActionPerformed(evt);
            }
        });
        meVendas.add(miConsultarVenda);

        barMenu.add(meVendas);

        meSobre1.setText("Consultar");
        meSobre1.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N

        miConCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        miConCliente.setText("Clientes");
        miConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConClienteActionPerformed(evt);
            }
        });
        meSobre1.add(miConCliente);

        miConLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livros.png"))); // NOI18N
        miConLivro.setText("Livros");
        miConLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConLivroActionPerformed(evt);
            }
        });
        meSobre1.add(miConLivro);

        miConCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categorias.png"))); // NOI18N
        miConCategoria.setText("Categorias");
        miConCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConCategoriaActionPerformed(evt);
            }
        });
        meSobre1.add(miConCategoria);

        miConVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendas.png"))); // NOI18N
        miConVendas.setText("Vendas");
        miConVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConVendasActionPerformed(evt);
            }
        });
        meSobre1.add(miConVendas);

        miConFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionarios.png"))); // NOI18N
        miConFuncionarios.setText("Funcionarios");
        miConFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConFuncionariosActionPerformed(evt);
            }
        });
        meSobre1.add(miConFuncionarios);

        barMenu.add(meSobre1);

        meSobre.setText("Sobre");
        meSobre.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N

        miInformações.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informacoes.png"))); // NOI18N
        miInformações.setText("Informações");
        miInformações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInformaçõesActionPerformed(evt);
            }
        });
        meSobre.add(miInformações);

        barMenu.add(meSobre);

        setJMenuBar(barMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void miAltCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltCadClienteActionPerformed
        FrCadCliente telaAlt = new FrCadCliente(this, rootPaneCheckingEnabled);

        telaAlt.setVisible(true);
    }//GEN-LAST:event_miAltCadClienteActionPerformed

    private void miLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLivrosActionPerformed
        FrCadLivros telaCadastro = new FrCadLivros(this, rootPaneCheckingEnabled);

        telaCadastro.setVisible(true);
    }//GEN-LAST:event_miLivrosActionPerformed

    private void miFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFuncionariosActionPerformed
        FrCadFuncionario telaCadastro = new FrCadFuncionario(this, rootPaneCheckingEnabled, 0);

        telaCadastro.setVisible(true);
    }//GEN-LAST:event_miFuncionariosActionPerformed

    private void miRegistarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistarVendaActionPerformed
        FrCadVenda telaVenda = new FrCadVenda(this, rootPaneCheckingEnabled);

        telaVenda.setVisible(true);
    }//GEN-LAST:event_miRegistarVendaActionPerformed

    private void miConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarVendaActionPerformed
        FrConVendas convenda = new FrConVendas(this, rootPaneCheckingEnabled);

        convenda.setVisible(true);
    }//GEN-LAST:event_miConsultarVendaActionPerformed

    private void miInformaçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInformaçõesActionPerformed
        FrInformacoes telaInformacoes = new FrInformacoes(this, rootPaneCheckingEnabled);

        telaInformacoes.setVisible(true);
    }//GEN-LAST:event_miInformaçõesActionPerformed

    private void miCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCategoriasActionPerformed
        FrCadGenero telaCategoria = new FrCadGenero(this, rootPaneCheckingEnabled);

        telaCategoria.setVisible(true);
    }//GEN-LAST:event_miCategoriasActionPerformed

    private void miConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConClienteActionPerformed
        FrConCliente telaCliente = new FrConCliente(this, rootPaneCheckingEnabled);

        telaCliente.setVisible(true);
    }//GEN-LAST:event_miConClienteActionPerformed

    private void miConLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConLivroActionPerformed
        FrConLivros telaLivros = new FrConLivros(this, rootPaneCheckingEnabled);

        telaLivros.setVisible(true);
    }//GEN-LAST:event_miConLivroActionPerformed

    private void miConCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConCategoriaActionPerformed
        FrConGenero telaGenero = new FrConGenero(this, rootPaneCheckingEnabled);

        telaGenero.setVisible(true);
    }//GEN-LAST:event_miConCategoriaActionPerformed

    private void miConVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConVendasActionPerformed
        FrConVendas telaVendas = new FrConVendas(this, rootPaneCheckingEnabled);

        telaVendas.setVisible(true);
    }//GEN-LAST:event_miConVendasActionPerformed

    private void miConFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConFuncionariosActionPerformed
        FrConFuncionario telaFunc = new FrConFuncionario(this, rootPaneCheckingEnabled);

        telaFunc.setVisible(true);
    }//GEN-LAST:event_miConFuncionariosActionPerformed

    private void miCadastrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarAutorActionPerformed

        FrCadAutor autor = new FrCadAutor(this, rootPaneCheckingEnabled);

        autor.setVisible(true);

    }//GEN-LAST:event_miCadastrarAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu meCadastro;
    private javax.swing.JMenu meSobre;
    private javax.swing.JMenu meSobre1;
    private javax.swing.JMenu meVendas;
    private javax.swing.JMenuItem miAltCadCliente;
    private javax.swing.JMenuItem miCadastrarAutor;
    private javax.swing.JMenuItem miCategorias;
    private javax.swing.JMenuItem miConCategoria;
    private javax.swing.JMenuItem miConCliente;
    private javax.swing.JMenuItem miConFuncionarios;
    private javax.swing.JMenuItem miConLivro;
    private javax.swing.JMenuItem miConVendas;
    private javax.swing.JMenuItem miConsultarVenda;
    private javax.swing.JMenuItem miFuncionarios;
    private javax.swing.JMenuItem miInformações;
    private javax.swing.JMenuItem miLivros;
    private javax.swing.JMenuItem miRegistarVenda;
    // End of variables declaration//GEN-END:variables
}
